### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TeslaOwnerTips**
Small format error that lead to incorrect url

### CODE REVIEW

**Comment by TeslaOwnerTips** [comment]
When viewed on my iPhone web browser

**Comment by madiele** [comment]
Will merge this later.

On another not I've missed this snippet in the original PR

`Mac: Make sure Rust is installed https://www.rust-lang.org`

which is in the docker section, that should not be required if using docker compose installation method, that makes sense only if installing vod2pod-rss natively on the machine, I would move that to the contributing.md where instruction about native installation are (I prefer the goto installation to be docker only to reduce misconfiguration errors)

**Comment by TeslaOwnerTips** [comment]
I agree about Rust. But I followed your instructions and it failed with Rust not found. Since I don’t use docker I assumed it was needed. So I installed it and went back to following your instructions. 

My Google located this post so without investing further I just installed Rust and went back to the instructions 

https://github.com/acheong08/ChatGPT/issues/572

**Comment by madiele** [comment]
Yeah docker can be summed up as a virtual machine (not really but it's close enough), it will install rust inside the virtual machine so no need to install it yourself.

Docker-compose needing rust to run sounds very weird to me, unfortunately I don't have an m1 mac so I can't make sure of it but it should work with no problem since I do support arm64 builds (I actually use them on my raspberry pi)

Did you get vod2pod-rss to run inside docker or natively on your Mac? The latter would explain why you got the error

**Pull request merged**
